Only report about errors if we actually have them

diff --git a/examples/dreamcast/Makefile b/examples/dreamcast/Makefile
--- a/examples/dreamcast/Makefile
+++ b/examples/dreamcast/Makefile
@@ -16,9 +16,9 @@ endif
 .PHONY: all $(DIRS)
 
 all: $(DIRS)
-	@echo "\n-------------------------------------------------"
-	@echo "$$(cat error_count.txt 2>/dev/null || echo 0) Error(s) occurred during the build process:"
 	@if [ -f errors.txt ]; then \
+		echo "\n-------------------------------------------------"; \
+		echo "$$(cat error_count.txt 2>/dev/null || echo 0) Error(s) occurred during the build process:"; \
 		cat errors.txt; \
 	fi
 	@rm -f errors.txt error_count.txt
