Update Makefile
Minor edit

diff --git a/examples/dreamcast/Makefile b/examples/dreamcast/Makefile
--- a/examples/dreamcast/Makefile
+++ b/examples/dreamcast/Makefile
@@ -5,7 +5,7 @@
 # Copyright (C) 2024 Andy Barajas
 #
 
-DIRS := 2ndmix basic libdream kgl hello sound png network vmu conio pvr video \
+DIRS = 2ndmix basic libdream kgl hello sound png network vmu conio pvr video \
 	   lua parallax modem dreameye sd g1ata lightgun keyboard sdl dev rumble \
 	   micropython
 
@@ -18,7 +18,7 @@ endif
 all: $(DIRS)
 	@if [ -f errors.txt ]; then \
 		echo "\n-------------------------------------------------"; \
-		echo "$$(cat error_count.txt 2>/dev/null || echo 0) Error(s) occurred during the build process:"; \
+		echo "$$(cat error_count.txt 2>/dev/null || echo 0) error(s) occurred during the build process:"; \
 		cat errors.txt; \
 	fi
 	@rm -f errors.txt error_count.txt
